'use client'
import { useState } from 'react'
import { Users, Link2, Clock, Copy, Check } from 'lucide-react'
import { useSession } from '@/hooks/useSession'
import { useToast } from '@/components/Toast'

export default function CollaborationPage() {
  const { schoolData, assignments } = useSession()
  const { toast } = useToast()

  const [copiedIdx, setCopiedIdx] = useState<number | null>(null)

  const teachers: { name: string; link?: string }[] =
    (schoolData.teachers ?? []).map((t: any) => ({
      name: t.name ?? t.id ?? 'Enseignant',
      link: undefined,  // links generated by backend when implemented
    }))

  const responded = 0 // placeholder until backend sends availability data

  async function copyLink(link: string, idx: number) {
    try {
      await navigator.clipboard.writeText(link)
      setCopiedIdx(idx)
      setTimeout(() => setCopiedIdx(null), 2000)
      toast('Lien copié')
    } catch {
      toast('Impossible de copier', 'error')
    }
  }

  return (
    <div className="animate-fade-in">
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Collaboration</h1>
        <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
          Gérez les invitations enseignants et leurs disponibilités
        </p>
      </div>

      {/* Stats row */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-8">
        {[
          { icon: Users,  label: 'Enseignants',        value: teachers.length.toString() },
          { icon: Link2,  label: 'Invitations créées', value: teachers.filter(t => t.link).length.toString() },
          { icon: Clock,  label: 'Réponses reçues',    value: responded.toString() },
        ].map(stat => (
          <div
            key={stat.label}
            className="bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-2xl p-5 shadow-sm flex items-center gap-4"
          >
            <div className="w-10 h-10 rounded-xl bg-teal-50 dark:bg-teal-900/30 text-teal-600 dark:text-teal-400 flex items-center justify-center flex-shrink-0">
              <stat.icon size={18} />
            </div>
            <div>
              <p className="text-2xl font-bold text-gray-900 dark:text-white">{stat.value}</p>
              <p className="text-xs text-gray-500 dark:text-gray-400 leading-tight">{stat.label}</p>
            </div>
          </div>
        ))}
      </div>

      {/* Teacher list */}
      <div className="bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-2xl shadow-sm p-5 sm:p-6">
        <div className="flex flex-wrap items-center justify-between gap-3 mb-4">
          <h2 className="font-semibold text-gray-800 dark:text-gray-200">Liste des enseignants</h2>
          <button
            className="px-4 py-2 bg-teal-600 hover:bg-teal-700 text-white text-sm rounded-xl transition-colors disabled:opacity-50"
            disabled={teachers.length === 0}
          >
            Envoyer des invitations
          </button>
        </div>

        {teachers.length === 0 ? (
          <p className="text-sm text-gray-400 dark:text-gray-500 italic text-center py-8">
            Aucun enseignant configuré. Commencez dans l'espace de travail.
          </p>
        ) : (
          <div className="divide-y divide-gray-100 dark:divide-gray-800">
            {teachers.map((t, i) => (
              <div key={i} className="flex flex-wrap items-center justify-between gap-3 py-3 first:pt-0 last:pb-0">
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-full bg-teal-100 dark:bg-teal-900/40 text-teal-700 dark:text-teal-300 flex items-center justify-center text-xs font-bold flex-shrink-0">
                    {t.name.charAt(0).toUpperCase()}
                  </div>
                  <div>
                    <p className="text-sm font-medium text-gray-900 dark:text-gray-100">{t.name}</p>
                    {t.link ? (
                      <p className="text-xs text-gray-400 dark:text-gray-500 font-mono truncate max-w-[200px]">
                        {t.link}
                      </p>
                    ) : (
                      <p className="text-xs text-gray-400 dark:text-gray-500 italic">Aucun lien généré</p>
                    )}
                  </div>
                </div>

                {t.link && (
                  <button
                    onClick={() => copyLink(t.link!, i)}
                    className="flex items-center gap-1.5 px-3 py-1.5 text-xs border border-gray-200 dark:border-gray-700 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors text-gray-600 dark:text-gray-400"
                  >
                    {copiedIdx === i
                      ? <><Check size={13} className="text-teal-500" /> Copié</>
                      : <><Copy size={13} /> Copier le lien</>
                    }
                  </button>
                )}

                {/* Availability badge */}
                <span className="text-xs px-2.5 py-1 rounded-full bg-gray-100 dark:bg-gray-800 text-gray-500 dark:text-gray-400">
                  En attente
                </span>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}
